metadata:
  fpe:
    mode: FF3-1  # Default mode for FPE (FF1 or FF3-1)
    tweak_length: 8  # Length of the tweak value
    key_length: 16  # Length of the encryption key
    key_env_var: FPE_KEY  # Environment variable to retrieve the encryption key

tables:
  - table_name: customer
    columns:
      - column_name: customer_id
        pii: Y
        masking_algorithm:
          type: fpe
          format: LETTERS
          parameters:
            length: 10
      - column_name: email
        pii: Y
        masking_algorithm:
          type: fpe
          format: EMAIL
      - column_name: birth_date
        pii: N
      - column_name: full_name
        pii: Y
        masking_algorithm:
          type: fpe
          format: LETTERS
        pre_masking_logic: "CONCAT(first_name, ' ', last_name)"
    extraction_logic:
      where_clause: |
        WHERE updated_at >= '{{ execution_date.subtract(days=7).strftime("%Y-%m-%d") }}'
        AND status = 'active'
    derived_columns:
      - new_column_name: customer_age
        sql_logic: "EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM birth_date)"