metadata:
  fpe:
    masking_type: ff3 # Library for masking FPE or ff3
    tweak_length: CBD09280979564 # Adds randomness to ensure unique output for identical inputs
    key_length: 16 # Length of the encryption key
    key_env_var: FPE_KEY # Environment variable to retrieve the encryption key
  strategy: upsert
  target_db: sqlite
  source_db: sqlite
  default_masking_algorithm: sha256  # Default masking algorithm for PII columns

tables:
  - table_name: customer
    schema: customer_schema
    primary_key: customer_id
    columns:
      - column_name: customer_id
        pii: Y
        masking_algorithm:
          type: fpe
          fpe_format: STRING # Mask customer ID using FPE to maintain consistency
      - column_name: email
        pii: Y
        masking_algorithm:
          type: fpe
          fpe_format: STRING # Mask email using FPE
      - column_name: birth_date
        pii: N  # No masking required
      - column_name: full_name
        pii: N  # No masking required